name: tale
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - xgboost=0.90
  - cython=0.29.14
  - dropbox=9.4.0
  - flask=1.1.1
  - nltk=3.4.4
  - numba=0.48.0
  - pandas=1.0.1
  - plotly=4.5.0
  - requests=2.22.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - spacy=2.2.3
  - tqdm=4.42.1
  - cmake=3.16.3
  - hdbscan=0.8.24
  - matplotlib=3.1.3
  - networkx=2.4
  - shap=0.34.0
  - umap-learn=0.3.10
  - lightgbm=2.3.1
  - pip:
    - psutil==5.6.7
    - scrapely==0.14.1
    - dcor==0.3
    - multicoretsne==0.1
    - skope-rules==1.0.1
    - tables==3.6.1
    - pattern3==3.0.0

